# Generated by Django 4.2.7 on 2023-11-11 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderedproducts_fixed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Новый'), (2, 'Принят'), (3, 'Передан курьеру'), (4, 'Выполнен')], db_index=True, default=1, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 0)], verbose_name='Зафиксированная цена'),
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='foodcartapp.orderdetails', verbose_name='заказ'),
        ),
    ]
