# Generated by Django 4.2.7 on 2023-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderdetails_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='firstname',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='lastname',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Новый'), (2, 'Принят'), (3, 'Передан курьеру'), (4, 'Выполнен')], db_index=True, default=1, verbose_name='Статус'),
        ),
    ]
