# Generated by Django 4.2.7 on 2023-11-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderdetails_comment_alter_orderdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Комментарий'),
        ),
    ]
