# Generated by Django 4.2.7 on 2023-11-11 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderdetails_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время звонка менеджера'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='payment_method',
            field=models.PositiveIntegerField(choices=[(1, 'Наличные'), (2, 'Электронно')], db_index=True, default=1, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время регистрации'),
        ),
    ]
